Практические задания к 5-му уроку
Fedortsov-AV/JS pull request #7
Opened 2021-04-04 10:19 UTC by Fedortsov-AV

/* По третьему заданию - добавление продуктов в карзину можно осуществлять через консоль test1.addInBasket(10), test2.addInBasket(10), test3.addInBasket(10). Отчистка корзины - basket.delAll()

2021-04-05 16:19 UTC, Om1X requested changes

2021-04-05 16:19 UTC, Om1X commented on lesson5(task1,2).js
> +const styleTable = `<style>
вот это явно не нужно, подключение и описание стилей нужно вынести в html

2021-04-05 16:19 UTC, Om1X commented on lesson5(task3).js
> +p.align = 'right';
логику связанную с функциональностью сущностей нужно хранить внутри объекта

2021-04-05 16:19 UTC, Om1X commented on lesson5(task3).js
> +    }
налицо дублирование логики, нужно вынести это в отдельный метод

2021-04-05 16:19 UTC, Om1X commented on lesson5(task3).js
> +  },
это все-таки больше функционал каталога а не одного товара

2021-04-07 12:01 UTC, Fedortsov-AV commented on lesson5(task1,2).js
> +const styleTable = `<style>
Внес тут только для того чтобы не заливать index.html

2021-04-07 12:37 UTC, Fedortsov-AV commented on lesson5(task3).js
> +p.align = 'right';
Убрал как метод объекта

2021-04-07 12:38 UTC, Fedortsov-AV commented on lesson5(task3).js
> +    }
Оптимизировал, добавил метод и вместо дублей логики - вызов метода

2021-04-07 12:38 UTC, Fedortsov-AV commented on lesson5(task3).js
> +  },
Удалил.....

2021-04-07 12:41 UTC, Fedortsov-AV reviewed
Изменил lesson5(task3).js

2021-04-08 21:28 UTC, merged